import type { Step } from "./mock-data";

// Scripted agent run. Each entry is appended to the timeline on a timer.
// `gate: true` means streaming pauses here until the user clicks Accept.
// `gateLabel` / `gateHint` customize the inline approval bar.
export const SCRIPT: (Step & {
  gate?: boolean;
  gateLabel?: string;
  gateHint?: string;
  delayMs?: number;
})[] = [
  {
    id: "s1",
    stageIndex: 0,
    title: "Understanding research goal",
    summary:
      "Parsed objective: publish a strong-venue paper on explainable AI for computer vision. Identified sub-goals: discovery, survey, experiment, writing, submission.",
    duration: "12s",
    status: "review",
    tool: {
      name: "Goal Parser",
      input: { goal: "Publish XAI-vision paper in a strong venue" },
      output: "5 sub-goals extracted, mapped to workflow stages 1–5.",
      sources: [],
      citations: [],
      timeMs: 12000,
      status: "done",
    },
    delayMs: 0,
    gate: true,
    gateLabel: "Confirm research goal",
    gateHint: "Approve the parsed objective before I begin literature search.",
  },
  {
    id: "s2",
    stageIndex: 1,
    title: "Searching arXiv, Semantic Scholar, Papers with Code",
    summary: "Retrieved 312 candidate papers, deduplicated to 184, ranked by relevance and recency.",
    duration: "28s",
    status: "review",
    sources: ["arXiv", "Semantic Scholar", "Papers with Code"],
    tool: {
      name: "Literature Scraper",
      input: { query: "explainable AI computer vision faithfulness", years: "2022-2025" },
      output: "184 papers, 4 clusters identified.",
      sources: ["arXiv", "Semantic Scholar", "Papers with Code"],
      citations: ["Koh et al. 2022", "Chen et al. 2023", "Adebayo et al. 2024"],
      timeMs: 28000,
      status: "done",
    },
    output: { kind: "literature" },
    delayMs: 1200,
    gate: true,
    gateLabel: "Approve literature coverage",
    gateHint: "Confirm the top papers look right before I extract gaps.",
  },
  {
    id: "s3",
    stageIndex: 1,
    title: "Extracting research gaps",
    summary:
      "Identified 4 underserved directions where faithfulness evaluation and human preference are not yet integrated with concept-based methods.",
    duration: "51s",
    status: "done",
    tool: {
      name: "Gap Extractor",
      input: { corpus: 184, lens: "evaluation + faithfulness + human-centered" },
      output: "4 high-signal gaps surfaced.",
      sources: ["arXiv", "Semantic Scholar"],
      citations: ["Adebayo 2024", "Hooker 2023"],
      timeMs: 51000,
      status: "done",
    },
    delayMs: 1400,
  },
  {
    id: "s4",
    stageIndex: 0,
    title: "Generating emerging research opportunities",
    summary:
      "Ranked 4 emerging directions by novelty, feasibility, citation momentum, and strategic fit. Top pick: evaluation-first faithfulness benchmarks.",
    duration: "1m 20s",
    status: "done",
    tool: {
      name: "Opportunity Ranker",
      input: { gaps: 4, weights: { novelty: 0.3, feasibility: 0.25, momentum: 0.2, fit: 0.25 } },
      output: "Ranked list with strategic-fit scores.",
      sources: ["arXiv", "Semantic Scholar", "Papers with Code"],
      citations: ["Koh 2022", "Adebayo 2024", "Chen 2023"],
      timeMs: 80000,
      status: "done",
    },
    output: { kind: "opportunities" },
    delayMs: 1400,
  },
  {
    id: "s5",
    stageIndex: 0,
    title: "Waiting for human approval",
    summary: "Pick a direction to commit the workspace to before I draft an experiment plan.",
    duration: "1m 42s",
    status: "waiting",
    output: { kind: "approval-opportunities" },
    gate: true,
    delayMs: 1200,
  },
  {
    id: "s6",
    stageIndex: 2,
    title: "Designing experiment",
    summary:
      "Drafted hypothesis, variables, baselines, and evaluation. Ran a situation diagnosis across data, method, reproducibility, compute, ethics, and publication.",
    duration: "2m 04s",
    status: "review",
    tool: {
      name: "Experiment Designer",
      input: { direction: "Evaluation-first faithfulness benchmark" },
      output: "Plan v1 + 6-axis diagnosis.",
      sources: ["arXiv"],
      citations: ["Adebayo 2024"],
      timeMs: 124000,
      status: "done",
    },
    output: { kind: "experiment" },
    delayMs: 1200,
    gate: true,
    gateLabel: "Approve experiment plan",
    gateHint: "Confirm hypothesis, dataset, and diagnosis before I run experiments.",
  },
  {
    id: "s7",
    stageIndex: 3,
    title: "Iterating with AI feedback and human revision",
    summary:
      "Ran 4 experiments. After AI feedback on Exp 2, faithfulness regularization weight was raised. Human revision on Exp 3 corrected the perturbation schedule. Objective progress +34%.",
    duration: "3m 18s",
    status: "review",
    tool: {
      name: "Situation Diagnoser",
      input: { experiments: 4 },
      output: "Convergence achieved; one open reproducibility item.",
      sources: [],
      citations: [],
      timeMs: 198000,
      status: "done",
    },
    output: { kind: "iteration" },
    delayMs: 1600,
    gate: true,
    gateLabel: "Approve iteration results",
    gateHint: "Sign off on convergence before I draft the abstract.",
  },
  {
    id: "s8",
    stageIndex: 4,
    title: "Drafting abstract from notes and experiment results",
    summary:
      "Synthesized abstract from method, results, and audit. Paragraph-level controls are available for revision.",
    duration: "44s",
    status: "review",
    tool: {
      name: "Abstract Writer",
      input: { style: "Concise conference", inputs: ["notes.md", "results.csv"] },
      output: "Draft v1 ready for paragraph-level review.",
      sources: [],
      citations: ["Koh 2022", "Adebayo 2024"],
      timeMs: 44000,
      status: "review",
    },
    output: { kind: "abstract" },
    delayMs: 1400,
    gate: true,
    gateLabel: "Approve abstract draft",
    gateHint: "Approve the draft to package the submission.",
  },
  {
    id: "s9",
    stageIndex: 5,
    title: "Preparing publication launchpad",
    summary:
      "Packaged arXiv, OpenReview, GitHub, and Overleaf handoffs. Matched paper against upcoming venues.",
    duration: "1m 09s",
    status: "review",
    tool: {
      name: "Conference Monitor",
      input: { topic: "XAI computer vision" },
      output: "3 venues matched; ICLR'25 strongest fit.",
      sources: ["openreview.net", "cvpr.thecvf.com", "facctconference.org"],
      citations: [],
      timeMs: 69000,
      status: "done",
    },
    output: { kind: "publish" },
    delayMs: 1500,
    gate: true,
    gateLabel: "Approve publication targets",
    gateHint: "Confirm the platform handoffs before I match venues.",
  },
  {
    id: "s10",
    stageIndex: 5,
    title: "Incoming conferences matched",
    summary: "Surfaced deadlines, format requirements, and suggested next actions per venue.",
    duration: "22s",
    status: "done",
    output: { kind: "conferences" },
    delayMs: 1100,
  },
  {
    id: "s11",
    stageIndex: 6,
    title: "Memory & Growing updated",
    summary:
      "Added people to connect with, papers to read, citation gaps, and a reproducibility reminder.",
    duration: "18s",
    status: "done",
    tool: {
      name: "Memory Tracker",
      input: { researcher: "you", topic: "Faithful-CBM" },
      output: "5 reminders queued.",
      sources: ["Semantic Scholar"],
      citations: [],
      timeMs: 18000,
      status: "done",
    },
    output: { kind: "memory" },
    delayMs: 1300,
  },
];
